name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clean
        run: xcodebuild -configuration Release clean
      - name: Build
        run: xcodebuild -configuration Release
      - name: Pack Application
        run: tar -C build/Release -zcvf MonitorPreview.tar.gz Monitor\ Preview.app
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: MonitorPreview.tar.gz
          name: MonitorPreview.tar.gz
